---
deployment:
  tasks:
    - export DEPLOYPATH=/home/powercut/public_html
    - /bin/mkdir -p $DEPLOYPATH/lang/en
    - /bin/cp $CPANEL_BASE_DIR/lang/en/kvkk.php $DEPLOYPATH/lang/en/kvkk.php
    - /bin/mkdir -p $DEPLOYPATH/resources/views/layouts
    - /bin/cp $CPANEL_BASE_DIR/resources/views/layouts/header.blade.php $DEPLOYPATH/resources/views/layouts/header.blade.php
