---
deployment:
  tasks:
    - export APPROOT=/home/powercut
    - /bin/mkdir -p $APPROOT/routes
    - /bin/cp $CPANEL_BASE_DIR/routes/web.php $APPROOT/routes/web.php
    - /bin/mkdir -p $APPROOT/app/Providers
    - /bin/cp $CPANEL_BASE_DIR/app/Providers/AppServiceProvider.php $APPROOT/app/Providers/AppServiceProvider.php
